apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: devourdrive-com-tls
spec:
  secretName: devourdrive-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: devourdrive.com
  dnsNames:
    - devourdrive.com
    - www.devourdrive.com
